/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MathBar {
        "last": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface QuestionBox {
    }
}
declare global {
    interface HTMLMathBarElement extends Components.MathBar, HTMLStencilElement {
    }
    var HTMLMathBarElement: {
        prototype: HTMLMathBarElement;
        new (): HTMLMathBarElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLQuestionBoxElement extends Components.QuestionBox, HTMLStencilElement {
    }
    var HTMLQuestionBoxElement: {
        prototype: HTMLQuestionBoxElement;
        new (): HTMLQuestionBoxElement;
    };
    interface HTMLElementTagNameMap {
        "math-bar": HTMLMathBarElement;
        "my-component": HTMLMyComponentElement;
        "question-box": HTMLQuestionBoxElement;
    }
}
declare namespace LocalJSX {
    interface MathBar {
        "last"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface QuestionBox {
    }
    interface IntrinsicElements {
        "math-bar": MathBar;
        "my-component": MyComponent;
        "question-box": QuestionBox;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "math-bar": LocalJSX.MathBar & JSXBase.HTMLAttributes<HTMLMathBarElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "question-box": LocalJSX.QuestionBox & JSXBase.HTMLAttributes<HTMLQuestionBoxElement>;
        }
    }
}
